"""Abstract base strategy — all strategies inherit from this."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from loopforge.models import (
    ActionStep,
    Constraints,
    Decision,
    LoopState,
    RoundResult,
    TargetSpec,
)


@dataclass
class ActionPlan:
    """A plan generated by the strategy for one round."""
    goal: str
    steps: list[str]
    reasoning: str = ""
    # Direct edit data (avoids second LLM call)
    filepath: str | None = None
    search: str | None = None
    replace: str | None = None


@dataclass
class ActionResult:
    """Result of executing a plan."""
    success: bool
    actions: list[ActionStep] = field(default_factory=list)
    error: str | None = None


@dataclass
class EvaluateResult:
    """Result of evaluating the outcome."""
    score: float  # 0-1
    raw_output: str = ""
    metrics: dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base for all loop strategies.

    Subclasses must implement: plan, act, evaluate, decide
    """

    name: str = "base"
    description: str = ""

    def __init__(self, llm, **kwargs):
        self.llm = llm

    @abstractmethod
    async def plan(self, state: LoopState) -> ActionPlan:
        """Analyze the current state and generate a plan for this round."""
        ...

    @abstractmethod
    async def act(
        self, plan: ActionPlan, state: LoopState
    ) -> ActionResult:
        """Execute the plan. May involve file I/O, shell commands, etc."""
        ...

    @abstractmethod
    async def evaluate(
        self, result: ActionResult, state: LoopState
    ) -> EvaluateResult:
        """Evaluate how good the result is. Returns a score 0-1."""
        ...

    @abstractmethod
    async def decide(
        self,
        score: float,
        history: list[RoundResult],
        constraints: Constraints,
    ) -> Decision:
        """Decide what to do next: continue, backtrack, change strategy, or stop."""
        ...
